data:
  type: cifar10
  train_dir: ./data/
  test_dir: ./data/
  lsun_categories_train: bedroom_train
  lsun_categories_test: bedroom_test
  img_size: 32
generator:
  name: resnet1
  kwargs:
    nfilter: 32
    nfilter_max: 256
discriminator:
  name: resnet1
  kwargs:
    nfilter: 32
    nfilter_max: 256
z_dist:
  type: gauss
  dim: 256
training:
  out_dir: output/
  out_basename: cifar_baseline_wganreal
  gan_type: wgan
  reg_type: real
  reg_param: 10.
  batch_size: 64
  nworkers: 32
  take_model_average: true
  model_average_beta: 0.999
  model_average_reinit: false
  monitoring: tensorboard
  sample_every: 1000
  inception_every: 10000
  save_every: 900
  backup_every: 100000
  restart_every: -1
  optimizer: rmsprop
  lr_g: 0.0001
  lr_d: 0.0001
  momentum_d: 0.
  weight_decay_d: 0.
  lr_anneal: 1.
  lr_anneal_every: 150000
  d_steps: 1
  equalize_lr: false
test:
  batch_size: 32
  sample_size: 15
  sample_nrow: 5
  use_model_average: true
  compute_inception: false
  conditional_samples: false
interpolations:
  nzs: 10
  nsubsteps: 75
