data:
  type: MoG
  train_dir: ./data/
  test_dir: ./data/
  lsun_categories_train: bedroom_train
  lsun_categories_test: bedroom_test
  img_size: 2
  shape: ring
  num_mixture: 8
  radius: 1
  std: 0.05

  # shape: grid
  # num_mixture: 25
  # radius: 0.2
  # std: 0.01
generator:
  name: mlp1
  kwargs:
    nfilter: 32
    nfilter_max: 256
discriminator:
  name: mlp1
  kwargs:
    nfilter: 32
    nfilter_max: 256
z_dist:
  type: gauss
  dim: 32
training:
  gan_type: wgan
  reg_type: wgangp
  reg_param: 10.
  nworkers: 0
  take_model_average: false
  model_average_beta: 0.999
  model_average_reinit: false
  monitoring: tensorboard
  sample_every: 1000
  inception_every: -1
  save_every: 900
  backup_every: 1000000
  restart_every: -1
  optimizer: rmsprop
  batch_size: 512 ### 
  lr_g: 0.0001
  lr_d: 0.0001
  out_dir: output/
  out_basename: MoG_
  pid_type: lsgan
  pv: 1.
  iv: 0.
  dv: 0.
  anneal_iv_factor: -1
  anneal_iv_every: 100000000
  anneal_iv_final: 0.1
  i_size: 512
  i_buffer_factor: 100
  i_buffer_onestep: 512
  momentum_d: 0. ###
  clip_d: 0. ###
  weight_decay_d: 0.0 ###
  regularize_output_d: 0. ###
  lr_anneal: 1.
  lr_anneal_every: 150000
  d_steps: 1
  equalize_lr: false
test:
  batch_size: 64
  sample_size: 15
  sample_nrow: 5
  use_model_average: true
  compute_inception: false
  conditional_samples: false
interpolations:
  nzs: 10
  nsubsteps: 75
